"""
src/track_analysis.py

Phase 4 - Track Analysis / Class Stabilization
------------------------------------------------
Purpose:
    YOLOv8's COCO classes are not reliable enough to distinguish an
    F1 race car from a truck consistently. The same physical F1 car
    may therefore be labelled "car" in one frame and "truck" in
    another.

    For this project, both classes represent the same canonical
    object type:

        car   -> race_car
        truck -> race_car

    This removes meaningless class flicker while preserving the
    track_id assigned by the tracker.

Usage:
    python src/track_analysis.py ^
        --csv outputs/tracking/tracks_F1_FullVideo_from3000.csv
"""

import argparse
import csv
import sys
from collections import Counter, defaultdict
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
TRACKING_OUT_DIR = PROJECT_ROOT / "outputs" / "tracking"

CANONICAL_CLASSES = {
    "car": "race_car",
    "truck": "race_car",
}


def load_tracks(csv_path: Path) -> list:
    """Load tracking rows from CSV."""
    with open(csv_path, "r", newline="") as f:
        reader = csv.DictReader(f)
        return list(reader)


def canonicalize_class(class_name: str) -> str:
    """
    Convert YOLO's ambiguous COCO classes into the project's
    canonical object class.
    """
    return CANONICAL_CLASSES.get(class_name, class_name)


def analyze_class_stability(rows: list) -> dict:
    """
    Analyze original YOLO labels per track.

    This is retained as a diagnostic so we can quantify how often
    YOLO alternates between 'car' and 'truck'.
    """
    by_track = defaultdict(list)

    for row in rows:
        by_track[row["track_id"]].append(row["class_name"])

    results = {}

    for track_id, labels in by_track.items():
        counts = Counter(labels)

        results[track_id] = {
            "total_frames": len(labels),
            "class_counts": dict(counts),
            "flickered": len(counts) > 1,
            "canonical_class": "race_car",
        }

    return results


def print_report(results: dict):
    """Print diagnostic report."""
    flickered = {
        tid: result
        for tid, result in results.items()
        if result["flickered"]
    }

    stable = {
        tid: result
        for tid, result in results.items()
        if not result["flickered"]
    }

    print("\n" + "=" * 60)
    print("TRACK CLASS STABILITY REPORT")
    print("=" * 60)

    print(f"Total tracks: {len(results)}")
    print(f"Stable original labels: {len(stable)}")
    print(f"Flickered original labels: {len(flickered)}")

    if flickered:
        print("\nOriginal YOLO label flickering:")

        for tid, result in sorted(
            flickered.items(),
            key=lambda x: -x[1]["total_frames"]
        ):
            print(
                f"  track_id {tid}: "
                f"{result['total_frames']} frames, "
                f"labels={result['class_counts']} "
                f"-> canonical='race_car'"
            )

    print("\nCanonical mapping:")
    print("  car   -> race_car")
    print("  truck -> race_car")

    print("\nAll tracked car/truck detections will therefore use:")
    print("  race_car")

    print("=" * 60 + "\n")


def write_stabilized_csv(
    rows: list,
    results: dict,
    out_path: Path
):
    """
    Write a stabilized CSV with a canonical_class column.

    Original class_name is preserved for diagnostic purposes.
    """
    if not rows:
        return

    fieldnames = list(rows[0].keys()) + ["canonical_class"]

    with open(out_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for row in rows:
            row_out = dict(row)

            original_class = row["class_name"]
            row_out["canonical_class"] = canonicalize_class(
                original_class
            )

            writer.writerow(row_out)

    print(f"Stabilized CSV saved to: {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Phase 4: Analyze YOLO class flicker and "
            "canonicalize car/truck as race_car."
        )
    )

    parser.add_argument(
        "--csv",
        type=str,
        required=True,
        help="Path to tracks_*.csv generated by tracker.py."
    )

    args = parser.parse_args()

    csv_path = Path(args.csv)

    if not csv_path.exists():
        print(f"ERROR: {csv_path} does not exist.")
        sys.exit(1)

    rows = load_tracks(csv_path)

    if not rows:
        print("No rows found in CSV.")
        sys.exit(1)

    results = analyze_class_stability(rows)

    print_report(results)

    out_path = (
        TRACKING_OUT_DIR
        / f"{csv_path.stem}_stabilized.csv"
    )

    write_stabilized_csv(rows, results, out_path)


if __name__ == "__main__":
    main()